# Generated by Django 4.0.4 on 2022-07-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebreak_quiz_backend', '0002_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
    ]
