# Generated by Django 3.2.14 on 2022-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebreak_quiz_backend', '0003_rename_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
